# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-09 15:32
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Layer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('objtype', models.CharField(max_length=32)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=32632)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
