# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-09 12:10
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ByggFlate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poly_field', models.FloatField()),
                ('poly_id', models.FloatField()),
                ('koordh', models.FloatField()),
                ('objtype', models.CharField(max_length=32)),
                ('byggtyp_nb', models.IntegerField()),
                ('byggstat', models.CharField(max_length=2)),
                ('byggnr', models.IntegerField()),
                ('sefrakkomm', models.IntegerField()),
                ('registreri', models.IntegerField()),
                ('husloepenr', models.IntegerField()),
                ('komm', models.CharField(max_length=4)),
                ('produkt', models.CharField(max_length=15)),
                ('versjon', models.CharField(max_length=50)),
                ('omradeid', models.CharField(max_length=4)),
                ('orgdatvert', models.CharField(max_length=50)),
                ('kopidato', models.CharField(max_length=20)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
    ]
