# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-09 16:44
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('layers', '0002_auto_20161009_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=''),
            preserve_default=False,
        ),
    ]
