# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-11 18:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layers', '0004_feature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='layer',
            name='geom',
        ),
        migrations.RemoveField(
            model_name='layer',
            name='objtype',
        ),
        migrations.AddField(
            model_name='layer',
            name='name',
            field=models.CharField(default='tst', max_length=255),
            preserve_default=False,
        ),
    ]
