# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-05 18:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_exercise_order'),
        ('layers', '0006_auto_20161011_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='exercise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.Exercise'),
        ),
    ]
