# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-16 15:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('layers', '0009_layer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layer',
            name='exercise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.Exercise'),
        ),
    ]
