# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-14 09:27
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20161211_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
