# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-14 10:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_auto_20161214_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='instruction',
            name='exercise',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='instructions', to='courses.Exercise'),
            preserve_default=False,
        ),
    ]
