# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-14 11:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0008_instruction_exercise'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstructionStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Completed'), (0, 'Not completed')], default=0)),
                ('instruction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Instruction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
