# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-14 12:15
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0009_instructionstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserExercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='instructionstatus',
            name='instruction',
        ),
        migrations.RemoveField(
            model_name='instructionstatus',
            name='user',
        ),
        migrations.AddField(
            model_name='exercise',
            name='map_center',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.DeleteModel(
            name='InstructionStatus',
        ),
        migrations.AddField(
            model_name='userexercise',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Exercise'),
        ),
        migrations.AddField(
            model_name='userexercise',
            name='instructions_completed',
            field=models.ManyToManyField(to='courses.Instruction'),
        ),
        migrations.AddField(
            model_name='userexercise',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
