# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-15 13:38
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_auto_20161214_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='instruction',
            name='completionArgs',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instruction',
            name='completionOperation',
            field=models.CharField(default='buffer', max_length=255),
            preserve_default=False,
        ),
    ]
