# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-16 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_remove_course_lessons_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='lessons_completed',
            field=models.ManyToManyField(to='courses.Lesson'),
        ),
    ]
