# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-16 15:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_enrollment_lessons_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='next_lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next', to='courses.Lesson'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='prev_lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prev', to='courses.Lesson'),
        ),
    ]
