# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-09 16:48
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0019_auto_20170309_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instruction',
            name='completionArgs',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
